import uuid
from typing import Protocol

from fastapi_pagination import Page, Params

from backend.core.lobby import Invitation, Lobby, LobbyChatMessage


class LobbyRepository(Protocol):
    def save_lobby(self, lobby: Lobby) -> None: ...

    def get_lobby(self, lobby_id: uuid.UUID) -> Lobby: ...

    def delete_lobby(self, lobby_id: uuid.UUID) -> None: ...

    def save_invitation(self, invitation: Invitation) -> None: ...

    def get_invitation(self, invitation_id: uuid.UUID) -> Invitation: ...

    def delete_invitation(self, invitation_id: uuid.UUID) -> None: ...

    def get_pending_invitations(self, user) -> list[Invitation]: ...

    def get_user_lobbies(self, user) -> list[Lobby]: ...

    def add_message(self, message: LobbyChatMessage) -> None: ...

    def get_messages(self, lobby_id: uuid.UUID, pagination_params: Params) -> Page: ...


__all__ = ["LobbyRepository"]
