from typing import Optional, Protocol

from .types import *


class Gameplay(Protocol):
    def reveal_one(self, cell: Cell) -> RevealedCell: ...
    def reveal_many(self, cell: Cell) -> list[RevealedCell]: ...
    def flag(self, cell: Cell) -> None: ...
    def remove_flag(self, cell: Cell) -> None: ...
    def use_hint(self) -> Optional[Cell]: ...
    def is_game_over(self) -> bool: ...
    def get_game_state(self) -> GameState: ...


__all__ = ["Gameplay"]
