"""User chat messages

Revision ID: b9a86e473fd8
Revises: 9f675e99b625
Create Date: 2025-12-06 01:23:15.818231

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b9a86e473fd8"
down_revision: Union[str, Sequence[str], None] = "9f675e99b625"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_chat_messages",
        sa.Column(
            "id",
            sa.String(length=32).with_variant(
                postgresql.UUID(as_uuid=False), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "from_user_id",
            sa.String(length=32).with_variant(
                postgresql.UUID(as_uuid=False), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "to_user_id",
            sa.String(length=32).with_variant(
                postgresql.UUID(as_uuid=False), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["from_user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["to_user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_chat_messages")
    # ### end Alembic commands ###
