"""Add flagged cells

Revision ID: dceb0fca8c2a
Revises:
Create Date: 2025-11-25 00:50:28.325801

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dceb0fca8c2a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "singleplayer_gameplays",
        sa.Column("flagged_cells", sa.JSON(), nullable=False, server_default="[]"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("singleplayer_gameplays", "flagged_cells")
    # ### end Alembic commands ###
