# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - minesweeper-backend

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create deployment package
        run: |
          mkdir deploy
          cp -r algorithms deploy/
          cp -r backend deploy/
          cp __init__.py backend.py requirements.txt deploy/

          sed -i 's|--extra-index-url https://download.pytorch.org/whl/cu129|--extra-index-url https://download.pytorch.org/whl/cpu|' deploy/requirements.txt
          sed -i '/^nvidia/d' deploy/requirements.txt

          rm -rf deploy/algorithms/tests/hyperparameter_optimization/hyperparameters
          rm -rf deploy/algorithms/models

          cd deploy
          zip -r ../app.zip .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6E46961A4AC3445CAA3070EA2349CCB9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3BA86F6624234EE3B46E4152F9839BB2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3001777EC26F4D25BF5CFD3B1B108C4D }}

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "minesweeper-backend"
          slot-name: "Production"
          package: ./app.zip
